---
- name: Load ServiceAccount Variables
  include_vars: vars/serviceaccount.yml
  when: enable_serviceaccount | bool

- name: Include CSV Validation Task
  include_tasks: tasks/serviceaccount/csv_validation.yml
  when: enable_serviceaccount | bool

- name: Include YAML Generation Task
  include_tasks: tasks/serviceaccount/generate_k8s.yml
  when: enable_serviceaccount | bool